# Generated by Django 5.2.8 on 2025-11-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="메인 문구")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="서브 제목(위)"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="설명 문구(밑)"
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="banner/", verbose_name="배너 이미지"),
                ),
            ],
        ),
    ]
