# Generated by Django 5.2.8 on 2025-11-15 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="이벤트")),
                ("start_date", models.DateField(verbose_name="시작일")),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="마감일"),
                ),
            ],
            options={
                "verbose_name": "학사 일정",
                "verbose_name_plural": "학사 일정",
                "ordering": ["start_date", "title"],
            },
        ),
    ]
