# Generated by Django 5.2.8 on 2025-11-14 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(max_length=300)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("opening_hours", models.CharField(blank=True, max_length=200)),
                ("image", models.ImageField(blank=True, null=True, upload_to="place/")),
                ("location_link", models.URLField(blank=True, null=True)),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("restaurant", "식당"),
                            ("cafe", "카페"),
                            ("bar", "주점"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlaceMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("menu_type", models.CharField(blank=True, max_length=50)),
                ("price", models.PositiveIntegerField()),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menus",
                        to="place.place",
                    ),
                ),
            ],
        ),
    ]
