# Generated by Django 5.2.8 on 2025-11-15 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("place", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="place",
            options={"ordering": ["name"]},
        ),
    ]
